### ISSUE TITLE
times out with large files?

### ISSUE THREAD

**Issue by shiffman** [grayleonard/node-youtube-resumable-upload#7]
I haven't had the chance to investigate this in more depth yet, but I'm experiencing an issue perhaps related to large file sizes?  Things work great for me with small videos but when I move to an 800 MB file, after a I get the following:

```
undefined
tokens:undefined
/path/node_modules/node-youtube-resumable-upload/index.js:25
		  'Authorization':		'Bearer ' + this.tokens.access_token,
		                  		                       ^
TypeError: Cannot read property 'access_token' of undefined
    at resumableUpload.initUpload (/path/node_modules/node-youtube-resumable-upload/index.js:25:46)
    at upload (/path/youtube_resumable.js:26:19)
    at /path/youtube_resumable.js:59:3
    at /path/youtube_resumable.js:51:5
    at null._onTimeout (/path/node_modules/google-auth-cli/lib/index.js:72:15)
    at Timer.listOnTimeout (timers.js:119:15)
```

The `expired_in` value for the token from Google is `3600`.  Which if in seconds would be an hour?  Am going to see if I can track if the error reproduces consistently at the same time.

Am going to keep working on this but let me know if you have any ideas, thanks!

**Comment by shiffman** [comment]
Ok, the issue is simply that in google-auth-cli a default "timeout" value is set to 5 minutes.

```javascript
var TIMEOUT = 5 * 60 * 1000;
```

This can be adjusted by passing in a custom timeout, i.e.

```javascript
var getTokens = function(callback) {
  googleauth({
      access_type: 'offline',
      scope: 'https://www.googleapis.com/auth/youtube.upload' //can do just 'youtube', but 'youtube.upload' is more restrictive
  },
  {   client_id: google_secrets.client_id, //replace with your client_id and _secret
      client_secret: google_secrets.client_secret,
      /****** Give each upload one hour ******/
      timeout: 60 * 60 * 1000,
      /****** Give each upload one hour ******/
     port: 3000
  },
  function(err, authClient, tokens) {
    console.log(tokens);
    callback(tokens);
    return;
  });
};
```
